[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "blue-yonder"
authors = [{name = "Alexander Fedotov", email = "alex.fedotov@aol.com"}]
dynamic = ["version", "description"]
